name:  Build OpenMapTile

env:
  BWXDevTargetBranch: bwxdev
  fullname: bwxtl

on:
  push:
    branches:
      - main


jobs:
  dev_docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        if: success()
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.BWX_DEV_ACR_URL }}
          username: ${{ secrets.BWX_DEV_ACR_USER }}
          password: ${{ secrets.BWX_DEV_ACR_PWD }}


      - name: Build and Push docker image
        run: "docker build -t bwxacr.azurecr.io/bwxdev/${{ env.fullname }}:${{ steps.define_env.outputs.github-sha-short }} .\ndocker push  bwxacr.azurecr.io/bwxdev/${{ env.fullname }}:${{ steps.define_env.outputs.github-sha-short }} \n"

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: 'Fujitsu-Blockchain/charts'
          ref: '${{ env.BWXDevTargetBranch }}'
          token: ${{ secrets.TALAL_TOKEN}}
      - name: Edit values
        uses: mikefarah/yq@v4.16.2
        with:
          cmd: yq e -i '.image.tag="'${{ steps.define_env.outputs.github-sha-short }}'"' 'hlf-frontend/${{ env.fullname }}-values.yaml'
      - name: commit frontend chart
        uses: EndBug/add-and-commit@v7.5.0
        with:
          cwd: './'
          message: Github Action has pushed a new image with commit hash "${{ github.sha }}"
          committer_name: GitHub Actions
          push: true
          branch: '${{ env.BWXDevTargetBranch}}'